
-- tables
-- Table: Country
CREATE TABLE Country (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL
);

-- Table: City
CREATE TABLE City (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    latitude decimal(9,6) NOT NULL,
    longitude decimal(9,6) NOT NULL,
    Country_id int NOT NULL,
    CONSTRAINT FK_City FOREIGN KEY (Country_id) REFERENCES Country (id)
);

CREATE TABLE Measurement (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datetime TIMESTAMP NOT NULL,
    temp decimal(6,2) NOT NULL,
    pressure int NOT NULL,
    humidity int NOT NULL,
    temp_min decimal(6,2) NOT NULL,
    temp_max decimal(6,2) NOT NULL,
    weather varchar(50) NOT NULL,
    weather_desc varchar(100) NOT NULL,
    wind_speed decimal(6,2) NOT NULL,
    wind_deg int NOT NULL,
    City_id int NOT NULL,
    CONSTRAINT FK_Measurement FOREIGN KEY (City_id) REFERENCES City (id)
);

INSERT INTO Country (id, name)
VALUES
    (1,'Czechia'),
    (2,'Slovakia'),
    (3,'Germany'),
    (4,'Austria'),
    (5,'Poland');

INSERT INTO City (name, latitude, longitude, Country_id)
VALUES
    ('Prague', 50.08804, 14.42076, 1),
    ('Bratislava', 48.14816, 17.10674, 2),
    ('Hamburg', 53.55073, 9.99302, 3),
    ('Berlin', 52.52437, 13.41053, 3),
    ('Vienna', 48.20849, 16.37208, 4),
    ('Warsaw', 52.22977, 21.01178, 5);

